config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "tweets#index"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :users
  resources :tweets
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet, counter_cache: true

  # Validations
  validates :body, length: { minimum: 1, maximum: 140 }
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  # Associations
  belongs_to :user
  has_many :comments, dependent: :destroy

  # Validations
  validates :body, length: { minimum: 1, maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Associactions
  has_many :tweets, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :cover

  after_create :attach_default

  # Validations
  validates :name, length: { minimum: 1 }
  # validates :email, :username, uniqueness: true
  # validates_format_of :email, with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/, on: :create, message: "is invalid"
  def attach_default
    return if self.cover.attached? 
    self.cover.attach(io: File.open("db/images/users/user_cover.png"), filename: "cover")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :authenticate_user!, except: %i[index show]

  protected
  # Para permitir mas parametros en un formulario
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username name cover])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username name cover])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new
    @comment.user_id = current_user.id
    @tweet = Tweet.find(params[:id])
    @comment.tweet= @tweet
    @comment.body = params[:body]
    
    if @comment.save
      redirect_to tweet_path(id:params[:id])
    else
      render "tweets/show", status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @tweet = @comment.tweet
    @comment.destroy
    redirect_to @tweet, status: :see_other
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @tweet = @comment.tweet
    if @comment.update(body:params[:comment][:body])
      redirect_to  @tweet
    else
      render "edit", status: :unprocessable_entity
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweet = Tweet.new
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comment = Comment.new
  end

  def create
    @tweet = Tweet.new
    @tweet.user_id = current_user.id
    @tweet.body = params[:tweet][:body]
    if @tweet.save
      redirect_to tweets_path
    else
      render "index", status: :unprocessable_entity
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end 

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(body:params[:tweet][:body])
      redirect_to  tweets_path
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to tweets_path, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%=form_with url: comments_path(id:tweet.id) do |f|%>
  <div class="flex gap-0_5 p-xs bg-white border-bg">      
    <%= image_tag(current_user.cover,:class =>"user-cover") if current_user.cover.attached?%>
    <div class="flex flex-column items-right w-full">
      <%=f.text_area :body, placeholder: "Remember to think before write...", class: "t-input mb-2 w-full"%>
      <%=f.submit "Comment",class: "button button--primary mb-4" %>
    </div>
  </div>
<%end%>

app/views/comments/edit.html.erb
<div class="container-lg center bg-white">
  <h1 class="content-lg p-1">Edit Comment</h1>
  <%= render "shared/error_messages", resource: @comment %>
  <div class="border-bg"><%= render "shared/form_edit", resource: @comment%></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetableIndividual</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-1">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <section class="section">
      <header class = "container">
      <nav class= "navbar">
        <ul class="flex gap-1 content-right items-center">
          <% if user_signed_in? %>
            <li> <%= link_to "Edit Profile", edit_user_registration_path, class:"primary-color" %> </li>
            <li class="button button--secondary">
              <%= link_to  "Log out", destroy_user_session_path, class: "primary-color", data: { turbo_method: :delete} %>
            </li>
          <% else %>
            <li class="button button--secondary">
              <%= link_to "Login", new_user_session_path, class: "primary-color" %>
            </li>
          <% end %>
        </ul>
      </nav>
      </header>
      <%= yield %>
    </section>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
    <h2>Unable to process your request. Try again.</h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

app/views/shared/_form_edit.html.erb
<div class="container-sm">
  <%=form_with model: resource do |f|%>
    <div class="input gap_zero items-left mt-1_625">
      <%=f.label :body, class: "content-sm"%>
      <%=f.text_area :body, placeholder: "Remember to think before write...",
                      class: "input__content input__container mb-2"%>
    </div>
    <div class="flex flex-center-items">
      <%=f.submit "Edit",class: "button button--primary mb-4" %>
    </div>
  <%end%>
</div>

app/views/tweets/_form.html.erb
<%=form_with model: tweet do |f|%>
  <div class="flex gap-0_5 p-xs bg-white border-bg">      
    <%= image_tag(current_user.cover,:class =>"user-cover") if current_user.cover.attached?%>
    <div class="flex flex-column items-right w-full">
      <%=f.text_area :body, placeholder: "Remember to think before write...", class: "t-input mb-2 w-full"%>
      <%=f.submit "Tweet",class: "button button--primary mb-4" %>
    </div>
  </div>
<%end%>

app/views/tweets/edit.html.erb
<div class="container-lg center bg-white">
  <h1 class="content-lg p-1">Edit Tweet</h1>
  <%= render "shared/error_messages", resource: @tweet %>
  <div class="border-bg"><%= render "shared/form_edit", resource: @tweet%></div>
</div>

app/views/tweets/index.html.erb
<div class="container center">
  <h1 class="content-lg bg-white p-1">Home</h1>
  <%= render "shared/error_messages", resource: @tweet %>
  <%= render "form", tweet: @tweet if user_signed_in? %>
  <div class="rectangle bg-2"></div>
  <% Tweet.order(:created_at).reverse.each do |t| %>
    <div class="flex gap-0_5 p-xs bg-white border-bg">      
      <%= image_tag(t.user.cover,:class =>"user-cover") if t.user.cover.attached?%>
      <div class="flex flex-column items-left w-full">
        <div class="flex gap-0_5">
          <%=tag.p t.user.name, class:"primary-text bold"%>
          <%=tag.p "@".concat(t.user.username), class:"secondary-text"%>
          <%=tag.p time_ago_in_words(t.created_at), class:"secondary-text"%>
        </div>
        <%=link_to "#{t.body}", t, class:"black mb-2"%>
        <div class="flex gap-0_625 items-center w-full">
          <%=link_to image_tag("icons/comments.svg"), t%>
          <%=tag.p t.comments_count %>
          <div class= "flex gap-1 w-full content-right">
            <% authorization = user_signed_in? ? current_user==t.user : false %>
            <%= link_to image_tag("icons/delete.svg"),t, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } if authorization%>
            <%= link_to image_tag("icons/edit.svg"), edit_tweet_path(t) if authorization%>
          </div>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/tweets/show.html.erb
<div class="container center">
  <h1 class="content-lg bg-white p-1">Tweet Detail</h1>
  <div class="flex gap-0_5 p-xs bg-white border-bg">      
      <%= image_tag(@tweet.user.cover,:class =>"user-cover") if @tweet.user.cover.attached?%>
      <div class="flex flex-column items-left w-full">
        <div class="flex gap-0_5">
          <%=tag.p @tweet.user.name, class:"primary-text bold"%>
          <%=tag.p "@".concat(@tweet.user.username), class:"secondary-text"%>
          <%=tag.p time_ago_in_words(@tweet.created_at), class:"secondary-text"%>
        </div>
        <%=tag.p @tweet.body, class:"black mb-2"%>
        <div class="flex gap-0_625 items-center w-full">
          <%=link_to image_tag("icons/comments.svg"), @tweet%>
          <%=tag.p @tweet.comments_count %>
        </div>
      </div>
  </div>
  <!--<div class="flex gap-0_5 p-xs">      
    <%=image_tag(@tweet.user.cover,:class =>"user-cover") if @tweet.user.cover.attached?%>
    <div class="flex flex-column items-left">
      <div class="flex gap-0_5">
        <%=link_to "#{@tweet.user.name}", "#", class:"primary-text bold"%>
        <%=tag.p "@".concat(@tweet.user.username), class:"secondary-text"%>
        <%=tag.p time_ago_in_words(@tweet.created_at), class:"secondary-text"%>
      </div>
      <%=tag.p @tweet.body%>
      <div class="flex gap-0_625">
        <%="Comments"%>
        <%=tag.p @tweet.comments.length%>
      </div>
    </div>
  </div>-->
  <div class="rectangle bg-2"></div>
  <%= render "shared/error_messages", resource: @comment %>
  <%= render "comments/form", tweet: @tweet if user_signed_in?%>

  <%@tweet.comments.reverse.each do |c|%>
    <div class="flex gap-0_5 p-xs bg-white border-bg">      
      <%=link_to image_tag(c.user.cover,:class =>"user-cover"), "#" if c.user.cover.attached?%>
      <div class="flex flex-column items-left w-full">
        <div class="flex gap-0_5">
          <%=link_to "#{c.user.name}", "#", class:"primary-text bold"%>
          <%=tag.p "@".concat(c.user.username), class:"secondary-text"%>
          <%=tag.p time_ago_in_words(c.created_at), class:"secondary-text"%>
        </div>
        <%=tag.p c.body, class:"black mb-2"%>
        <% authorization = user_signed_in? ? current_user==c.user : false %>
        <div class= "flex gap-1 w-full content-right">
          <%= link_to image_tag("icons/delete.svg"),c, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } if authorization%>
          <%= link_to image_tag("icons/edit.svg"), edit_comment_path(c) if authorization %>
        </div>
      </div>
    </div>
  <%end%>
</div>